---
- hosts: localhost
  any_errors_fatal: true
  gather_facts: true

  vars: 
    destfolder: '/Volumes/RemoteStorage/'  #Path to backup folder location
    app_folders:
      - { name: 'icloud', dst_path: 'icloud', src_path: '~/Library/Mobile Documents/com~apple~CloudDocs/' }  #Default path to icloud data folder location
      - { name: 'iphoto', dst_path: 'iphoto', src_path: '~/Pictures' }  #Default path to iphoto folder location
      - { name: 'dropbox', dst_path: 'dropbox', src_path: '~/Dropbox' } #Default path to Dropbox location
      - { name: 'github', dst_path: 'github', src_path: '~/Documents/Github' } #Github location

  pre_tasks: 

  - name: Checking for External Drive Connectivity
    stat: 
      path: '{{ destfolder }}'
    register: destpath

  - name: Drive Connectivity Failsafe
    fail:
      msg: External Hard Drive Is Not Connected
    when: not destpath.stat.exists

  tasks:

  - name: Synchronizing Daily Backup
    synchronize:
      src: '{{ item.src_path }}'
      dest: '{{ destfolder }}/backup/daily/{{ item.dst_path }}'
      delete: yes
      recursive: yes
    loop: '{{ app_folders }}'
    loop_control: 
      label: '{{ item.name }}'
    when: destpath.stat.exists

  - name: Synchronizing Friday Weekly Backup
    synchronize:
      src: '{{ destfolder }}/backup/daily/'
      dest: '{{ destfolder }}/backup/weekly/'
      delete: yes
      recursive: yes
    when: (destpath.stat.exists) and (ansible_date_time.weekday == 'Friday')

  - name: Checking For Monthly Backup Directory
    file:
      path: '{{ destfolder }}/backup/monthly/'
      state: directory
      mode: '0755'
    when: (destpath.stat.exists) and (ansible_date_time.day == '01')

  - name: Archiving Monthly Backup
    archive:
      path: '{{ destfolder }}/backup/daily/'
      dest: '{{ destfolder }}/backup/monthly/{{ ansible_date_time.month }}_backup.zip'
      format: zip
    when: (destpath.stat.exists) and (ansible_date_time.day == '01')